Из за особой природы потоков нельзя перехватить исключение, созданное в потоке. 
Как только исключение появляется в методе run, оно сразу передается на консоль. 
Решить эту проблему можно с помошью объектов Executor. Рассмотрим это на примере 
В классе ExceptionThread.java мы получаем не перехваченное исключение, не смотря на то что мы заключили его в блок try-catch
Решение данной проблемы в примере CaptureUncaughtException.java

Для этого используем интерфейс Thread.UncaughtExceptionHandler , который позволяет связать с каждым объектом Thread обработчик исключения.